### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by abraxxa** [jplindstrom/p5-Test-DBIC-ExpectedQueries#5]
`Test::DBI::ExpectedQueries` should read `Test::DBIC::ExpectedQueries` in the `Flexible` synopsis section.

**Comment by abraxxa** [comment]
https://metacpan.org/pod/Dist::Zilla::Plugin::Test::Synopsis helps you find and prevent such errors.

**Comment by j1n3l0** [comment]
This pull request #4 fixes that issue @jplindstrom 🙃

**Comment by jplindstrom** [comment]
Thanks @j1n3l0, merged. Not sure why I didn't see this earlier.
